name: Review Issues

on:
  issues:
    types: [opened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Token
        uses: tibdex/github-app-token@v2
        id: generate
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Review Issues
        uses: ./
        with:
          github_token: ${{ steps.generate.outputs.token }}
          openai_base_url: ${{ secrets.OPENAI_BASE_URL }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_model: ${{ vars.OPENAI_MODEL }}
          openai_temperature: ${{ vars.OPENAI_TEMPERATURE }}
          openai_top_p: ${{ vars.OPENAI_TOP_P }}
          openai_frequency_penalty: ${{ vars.OPENAI_FREQUENCY_PENALTY }}
          openai_presence_penalty: ${{ vars.OPENAI_PRESENCE_PENALTY }}
          system_prompt: ${{ vars.ISSUES_SYSTEM_PROMPT }}
          available_tools: ${{ vars.ISSUES_AVAILABLE_TOOLS }}
          user_input: |
            Please review this issue:
            Title: "${{ github.event.issue.title }}"
            Content: "${{ github.event.issue.body }}"
